apiVersion: v1alpha1
kind: Setting
metadata:
  name: ado-zero-setting
spec:
  forms:
    - group: layout
      label: 布局设置
      formSchema:
        - $formkit: select
          name: main_width
          label: 主体内容显示宽度
          value: ""
          options:
            - label: "常规"
              value: ""
            - label: "中等"
              value: "medium"
            - label: "较宽"
              value: "large"
        - $formkit: radio
          name: bg_texture
          label: 背景纹理
          value: false
          options:
            - label: "开启"
              value: true
            - label: "关闭"
              value: false
    - group: beian
      label: 备案信息
      formSchema:
        - $formkit: text
          name: icp_text
          label: ICP备案号
          placeholder: "请输入ICP备案号"
        - $formkit: text
          name: icp_link
          label: ICP备案跳转链接
          value: https://beian.miit.gov.cn/
    - group: pendant
      label: 节日挂件
      formSchema:
        - $formkit: radio
          name: lantern
          label: 灯笼状态
          value: false
          help: "宽度小于1200px时不显示挂件"
          options:
            - label: "开启"
              value: true
            - label: "关闭"
              value: false
        - $formkit: select
          name: festival
          label: 选择节日
          value: "default"
          options:
            - label: "默认"
              value: "default"
            - label: "春节"
              value: "spring"
            - label: "国庆"
              value: "national"